version: '3.8'

services:
  laravel:
    build:
      context: .
      dockerfile: docker/Dockerfile  # Ajuste para la ruta correcta del Dockerfile
    volumes:
      - ./:/var/www
    ports:
      - "9000:9000"
    env_file:
      - .env  # Cargando variables de entorno desde .env en la misma carpeta

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  # Contraseña para el usuario root
      MYSQL_DATABASE: codeweb     # Base de datos que usarás
      MYSQL_USER: root            # Usuario que usarás
      MYSQL_PASSWORD: ""          # Contraseña vacía (según tu .env)
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


